import React from 'react'
import styles from '../../styles/Movies.module.css'
import Head from 'next/head'

export default function Movies() {
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>Movies</div>

    </>
  )
}
